Add dump to aft
awans/aft pull request #38
Opened 2020-09-16 21:44 UTC by chasehensel

https://drive.google.com/file/d/1MAParaz21AhW4LA-xm2WsYrsQIAqFmsa/view?usp=sharing

2020-09-17 02:56 UTC, awans requested changes
you're right that this is a bit overwhelming in its current form. 

I can think of two ways to improve it:

1. Parse and format the GUIDs - the keys in Hold are raw bytes, but there's a method in Hold that can convert them back into GUIDs (if you select the right substring). 

2. Add some formatting - new lines and indentation (ie a pretty-print) would go a long way towards making this more usable.

2020-09-17 02:56 UTC, awans commented on internal/db/schema.go
> +func (s *Schema) String() string {
not sure this should be on schema (vs just DB or Tx)

2020-09-21 16:51 UTC, chasehensel commented
@awans should be good now

2020-09-21 18:43 UTC, awans approved these changes
LGTM

2020-09-21 18:45 UTC, merged